# Generated by Django 5.0.7 on 2024-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo_uri', models.URLField()),
                ('club_state', models.CharField(max_length=100)),
            ],
        ),
    ]
